# Generated by Django 3.2.15 on 2022-12-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_upload',
            old_name='my_file',
            new_name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='file_name',
        ),
    ]
